translations = {
    "en": {
        "welcome": "Welcome to TaxNerdGPT with Life-Planner!",
        "roadmap_title": "Your Detailed Life-Planner Roadmap:",
        "age": "Age",
        "savings_target": "Suggested Yearly Savings",
        "options": "How can I help you today?",
        "menu_options": [
            "1. TaxNerd Questionnaire",
            "2. Create a Life-Planner Roadmap",
            "3. View an inspiring scripture",
            "4. Exit"
        ],
        "invalid_choice": "Invalid choice. Please try again.",
        "exit_message": "Thank you for using TaxNerdGPT with Life-Planner. Have a blessed day!",
        "enter_age": "Enter your current age: ",
        "enter_career": "Enter the type of career you want (e.g., IT, healthcare, education): ",
        "enter_house_goal": "At what age do you plan to purchase a house? ",
        "enter_retirement_age": "At what age do you plan to retire? ",
        "enter_savings_goal": "Enter your retirement savings goal (e.g., 1000000 for $1,000,000): ",
        "marriage_plan": "Do you plan on getting married? (yes/no): ",
        "kids_plan": "Do you want to have kids? (yes/no): ",
        "pets_plan": "Do you want pets? (yes/no): ",
        "dream_car": "What is your dream car? ",
        "dream_car_age": "At what age do you want to purchase your dream car? ",
        "start_business": "Do you want to start a business? (yes/no): ",
        "business_age": "At what age do you plan to start your business? ",
        "college_plan": "Do you want to go to college? (yes/no): ",
        "desired_location": "Where would you like to live (e.g., city, state, or country)? ",
        "fetching_insights": "Fetching insights for {category}...",
        "insights_title": "{category} Insights:",
        "summary_title": "{category} Summary:",
        "scripture_message": "Here's an inspiring scripture for you:",
        "tax_analysis_start": "Let's start with the TaxNerd Questionnaire.",
        "tax_analysis_email": "Enter the recipient's email address to send the results as a PDF: ",
        "tax_analysis_sent": "Your tax analysis has been emailed!",
        "help_message": "Here are some things you can ask me:",
        "help_options": [
            "- 'Can you help me with tax analysis?'",
            "- 'I want to create a life plan.'",
            "- 'Show me a random scripture.'",
            "- 'Exit' to quit the program."
        ],
        "unknown_command": "I'm sorry, I didn't understand that. Type 'help' to see what I can do.",
        "access_prompt": "Which Life Planner(s) do you have access to?",
        "access_full": "Full Life Planner",
        "access_21day": "21-Day Planner",
        "access_3day": "3-Day Planner",
        "access_you_have": "You have access to:",
        "enter_numbers": "Enter numbers separated by commas (e.g., 1,2):",
        "save_pdf_prompt": "Would you like to save this planner as a PDF? (yes/no): ",
        "pdf_saved": "PDF saved as {filename}",
        "yes": "yes",
        "no": "no",
        "continue_prompt": "Press Enter to continue...",
        "planner_21day_title": "21-Day Life Planner:",
        "planner_3day_title": "3-Day Life Planner:"
    },
    "es": {
        "welcome": "¡Bienvenido a TaxNerdGPT con el Planificador de Vida!",
        "roadmap_title": "Tu Planificador de Vida Detallado:",
        "age": "Edad",
        "savings_target": "Ahorros Anuales Sugeridos",
        "options": "¿Cómo puedo ayudarte hoy?",
        "menu_options": [
            "1. Cuestionario de TaxNerd",
            "2. Crear un Planificador de Vida",
            "3. Ver una escritura inspiradora",
            "4. Salir"
        ],
        "invalid_choice": "Opción inválida. Por favor, inténtalo de nuevo.",
        "exit_message": "Gracias por usar TaxNerdGPT con el Planificador de Vida. ¡Que tengas un día bendecido!",
        "enter_age": "Ingrese su edad actual: ",
        "enter_career": "Ingrese el tipo de carrera que desea (por ejemplo, TI, salud, educación): ",
        "enter_house_goal": "¿A qué edad planea comprar una casa? ",
        "enter_retirement_age": "¿A qué edad planea jubilarse? ",
        "enter_savings_goal": "Ingrese su meta de ahorros para la jubilación (por ejemplo, 1000000 para $1,000,000): ",
        "marriage_plan": "¿Planea casarse? (sí/no): ",
        "kids_plan": "¿Quiere tener hijos? (sí/no): ",
        "pets_plan": "¿Quiere tener mascotas? (sí/no): ",
        "dream_car": "¿Cuál es su auto soñado? ",
        "dream_car_age": "¿A qué edad quiere comprar su auto soñado? ",
        "start_business": "¿Quiere iniciar un negocio? (sí/no): ",
        "business_age": "¿A qué edad planea iniciar su negocio? ",
        "college_plan": "¿Quiere ir a la universidad? (sí/no): ",
        "desired_location": "¿Dónde le gustaría vivir (por ejemplo, ciudad, estado o país)? ",
        "fetching_insights": "Obteniendo información para {category}...",
        "insights_title": "Información sobre {category}:",
        "summary_title": "Resumen de {category}:",
        "scripture_message": "Aquí tienes una escritura inspiradora:",
        "tax_analysis_start": "Comencemos con el Cuestionario de TaxNerd.",
        "tax_analysis_email": "Ingrese el correo electrónico del destinatario para enviar los resultados como un PDF: ",
        "tax_analysis_sent": "¡Su análisis fiscal ha sido enviado por correo electrónico!",
        "help_message": "Aquí hay algunas cosas que puedes pedirme:",
        "help_options": [
            "- '¿Puedes ayudarme con el análisis fiscal?'",
            "- 'Quiero crear un plan de vida.'",
            "- 'Muéstrame una escritura inspiradora.'",
            "- 'Salir' para cerrar el programa."
        ],
        "unknown_command": "Lo siento, no entendí eso. Escribe 'ayuda' para ver lo que puedo hacer.",
        "access_prompt": "¿A qué Planificador de Vida tiene acceso?",
        "access_full": "Planificador de Vida Completo",
        "access_21day": "Planificador de 21 Días",
        "access_3day": "Planificador de 3 Días",
        "access_you_have": "Tiene acceso a:",
        "enter_numbers": "Ingrese los números separados por comas (ejemplo: 1,2):",
        "save_pdf_prompt": "¿Desea guardar este planificador como PDF? (sí/no): ",
        "pdf_saved": "PDF guardado como {filename}",
        "yes": "sí",
        "no": "no",
        "continue_prompt": "Presione Enter para continuar...",
        "planner_21day_title": "Planificador de Vida de 21 Días:",
        "planner_3day_title": "Planificador de Vida de 3 Días:"
    }
}